### ISSUE TITLE
Typo in spanish

### ISSUE THREAD

**Issue by octavioamu** [cyanharlow/purecss-zigario#1]
The correct word in spanish should be "tratamiento" and not "tratiamento"

_Disclaimer: this issue was just for fun and with the typo I found it more authentic. Loved the work and the level of details!!!_ 😃

**Comment by cyanharlow** [comment]
@octavioamu Thank you for the correction! It's probably bad enough that I incorporated a language I don't even speak into this art piece, so I'd hate to offend anyone further by butchering it. I've pushed the fix <a href="http://diana-adrianne.com/purecss-zigario/">live</a> now. Thank you again!
